export const STATUSES=['To Apply','Applied','Interviewing','Rejected','Needs Follow-up'];
export const PRIORITIES=['Top','High','Normal'];
export const SOURCE='Manual entry';
const base={location:'',appliedDate:'',requisitionId:'',link:'',linkLabel:'',linkNote:'',notes:'',followUpDate:'',priority:'Normal',source:SOURCE,updatedAt:'',history:[]};
export const SEED=[];
export function safeLink(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function validateRows(rows){
 if(!Array.isArray(rows)||rows.length>10000)throw Error('Choose a backup with an applications array (maximum 10,000 roles).');
 const ids=new Set();return rows.map(r=>{if(!r||typeof r!=='object'||typeof r.company!=='string'||!r.company.trim()||typeof r.role!=='string'||!r.role.trim()||!STATUSES.includes(r.status)||!PRIORITIES.includes(r.priority))throw Error('Every role needs a company, role, valid status and priority.');if(typeof r.id!=='string'||!r.id||ids.has(r.id))throw Error('Every role must have a unique ID.');ids.add(r.id);const out={...base,id:r.id};for(const k of ['company','role','location','appliedDate','requisitionId','link','linkLabel','linkNote','notes','followUpDate','source','updatedAt','evidence','lastStatusEventAt','appliedDateSource'])out[k]=typeof r[k]==='string'?r[k]:'';for(const k of ['appliedDate','followUpDate'])if(out[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(out[k]))throw Error('Dates must use YYYY-MM-DD.');out.link=safeLink(out.link);out.status=r.status;out.priority=r.priority;out.hasApplied=r.status==='To Apply'?false:r.status==='Needs Follow-up'?Boolean(r.hasApplied):true;out.history=Array.isArray(r.history)?r.history.filter(h=>h&&typeof h==='object'):[];if(r.mailEvidence&&typeof r.mailEvidence==='object')out.mailEvidence={summary:String(r.mailEvidence.summary||''),messageId:/^[a-f0-9]+$/i.test(r.mailEvidence.messageId||'')?r.mailEvidence.messageId:'',at:String(r.mailEvidence.at||''),eventId:String(r.mailEvidence.eventId||'')};return out;});
}
export function filteredRows(rows,{view='All applications',query='',status='',priority='',company='',sort='priority'}={}){const q=query.trim().toLowerCase();return rows.filter(r=>(view==='All applications'||r.status===view)&&(!status||r.status===status)&&(!priority||r.priority===priority)&&(!company||r.company===company)&&(!q||[r.company,r.role,r.location,r.requisitionId,r.notes].join(' ').toLowerCase().includes(q))).sort((a,b)=>sort==='company'?a.company.localeCompare(b.company)||a.role.localeCompare(b.role):sort==='status'?STATUSES.indexOf(a.status)-STATUSES.indexOf(b.status):sort==='date'?(b.appliedDate||'').localeCompare(a.appliedDate||''):PRIORITIES.indexOf(a.priority)-PRIORITIES.indexOf(b.priority));}
export function changeStatus(row,status){return {...row,status,hasApplied:status==='To Apply'?false:status==='Needs Follow-up'?row.hasApplied:true,appliedDate:status==='To Apply'?'':row.appliedDate,updatedAt:new Date().toISOString(),history:[...row.history,{from:row.status,to:status,at:new Date().toISOString(),source:'manual'}]};}
